### ISSUE TITLE
Add support to share RuleGroup by multiple WAF

### ISSUE THREAD

**Issue by chladic** [crowdsecurity/cs-aws-waf-bouncer#13]
Hello crowdsec team,

would be possible to add feature where I would be able to share RuleGroup created by bouncer to multiple WAFs ?

As discussed with @blotus support for multiple WAF names
```
waf_config:
  - web_acl_name: [ "first_waf_acl","second_waf_acl" ] 
    rule_group_name: rule_group_shared
    scope: REGIONAL
    ipset_prefix: crowdsec-ipset-web
```
or something like this where bouncer dont remove RuleGroup (not so nice as first one)
```
waf_config:
  - web_acl_name: first_waf_acl
    rule_group_name: rule_group_shared
    rule_group_type: static
    scope: REGIONAL
    ipset_prefix: crowdsec-ipset-web
```

Many thanks for this
