### ISSUE TITLE
Capacity parameter isn't optional

### ISSUE THREAD

**Issue by AlexeyDemidov** [crowdsecurity/cs-aws-waf-bouncer#80]
With the following config, I'm getting an API error:

```
---
  api_key: {{ API_KEY }}
  api_url: {{ API_URL }}
  update_frequency: 10s
  waf_config:
    - web_acl_name: {{ WEBACLNAME }}
      fallback_action: captcha
      rule_group_name: crowdsec-rule-group-cloudfront
      scope: CLOUDFRONT
      ipset_prefix: crowdsec-ipset-cf
```

```
time="2025-06-18T07:06:37Z" level=info msg="Starting crowdsec-aws-waf-bouncer v0.1.9-06cbe7b292f9eeba5972e0e5c9bd422740832aca"
time="2025-06-18T07:06:37Z" level=info msg="Using API key auth"
time="2025-06-18T07:06:38Z" level=fatal msg="could not initialize waf instance: failed to create RuleGroup crowdsec-rule-group-cloudfront: InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateRuleGroupInput.Capacity.\n"
```

Adding explicit `capacity: 300` to the `waf_config` fixes the issue.
